#page title
page_title                                : TopSpin                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1534058819                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/id1534058819                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : #https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Top Spin                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : $2.99                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Top Spin is a dedicated Table Tennis score tracker. Simply increment the score through each rally. Top Spin will keep the score, tell you who is serving, and remind you that it's match point! Want to up your game? Top Spin also records workouts during your match. Take advantage of advanced tracking with the Apple Watch and close your rings! 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Will Brandin                                
your_link                                 :                      
your_city                                 : Bozeman                                
email_address                             : william.brandin@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : willBrandin
github_username                           : willbrandin
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Apple Watch Workout
    description                           : Workouts link with each match letting you know how many calories you burned as well as your heart rate.
    fontawesome_icon_name                 : running
    
  - title                                 : iOS Specific Design
    description                           : Design that feels natural and congruent to the iOS experience. 
    fontawesome_icon_name                 : apple

  - title                                 : Widgets
    description                           : Home Screen widgets allow you to see your monthly summary for your matches.
    fontawesome_icon_name                 : square

  - title                                 : Dark Mode
    description                           : If you like leaving your phone on dark mode, you will love TopSpin.
    fontawesome_icon_name                 : adjust

  - title                                 : Universal App
    description                           : Available on iPhone and iPad!
    fontawesome_icon_name                 : tablet

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000"

link_color                                : "#FF453A"

app_title_color                           : "#fff"
app_price_color                           : "#fff"
app_description_color                     : "#fff"

feature_title_color                       : "#fff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FF453A"
feature_icons_background_color            : "#222"

social_icons_foreground_color             : "#FF453A"
social_icons_background_color             : "#222"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
